### ISSUE TITLE
Blender 2.78c is not updated to version 2.79

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.blender.Blender#1]
hi, i tried to update blender 2.78c to 2.79, but it has a error and the update does not take place

**Comment by bochecha** [comment]
Yeah, I haven't built the update yet.

I probably won't have any time to do it before next Monday, so if someone wants to beat me to it I'll be happy to review a pull request. 🙂

**Comment by Lvaskz** [comment]
thanks

2017-09-22 1:48 GMT-06:00 Mathieu Bridon <notifications@github.com>:

**Comment by bochecha** [comment]
Blender 2.79 is building, it should land in Flathub soon if all goes well.

https://flathub.org/builds/#/builders/1/builds/466
