### ISSUE TITLE
Fix the appdata file

### ISSUE THREAD

**Issue by bochecha** [flathub/org.blender.Blender#13]
@TingPing pointed out our appdata file is incorrect on a few levels:

* it uses the old format
* it points to `blender.desktop` which gets renamed during the build
* it is missing a `launchable` tag

We should fix it.

Unfortunately the upstream one, while better, is also incorrect:

* `<launchable type="desktop"` should be `<launchable type="desktop-id"` ([docs](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html#tag-dapp-launchable))
* the `launchable` id needs to be renamed to `org.blender.Blender.desktop`

cc-ing @PointedStick who sent the appdata file upstream

**Comment by TingPing** [comment]
> it uses the old format

`appstream-util upgrade` btw.

**Comment by Pointedstick** [comment]
I don't think the launchable ID can be `org.blender.Blender.desktop` because that's not the name of their desktop file. It's still `blender.desktop`.

**Comment by bochecha** [comment]
> I don't think the launchable ID can be org.blender.Blender.desktop because that's not the name of their desktop file. It's still blender.desktop.

But it needs to be in the Flatpak build. Whether that goes upstream or not is a different question of course, but this being the bug tracker for the Flatpak build, I'm writing down here what I need to do for the Flatpak build. :wink:

**Comment by Pointedstick** [comment]
Submitted a fix for the `launchable` tag upstream: https://developer.blender.org/D3065#72995

Renaming their desktop file is on my to-do list, but I'm trying to build trust and confidence over time rather than doing too much at once and getting shut down.

**Comment by bochecha** [comment]
> Renaming their desktop file is on my to-do list, but I'm trying to build trust and confidence over time rather than doing too much at once and getting shut down.

That's fine. Thank you for doing this. :slightly_smiling_face:
