### ISSUE TITLE
Splash screen metadata

### ISSUE THREAD

**Issue by afranke** [flathub/org.blender.Blender#14]
On the splash screen, there are versionning metadata in the top right corner. The Flatpak version states “Hash: unknown\Branch: unknown”. The upstream static build has (for 2.79b which is slightly more recent than the current 2.79 in flathub) “Date 2018-03-22 14:10\nHash: f4dc9f9d68b”.

**Comment by bochecha** [comment]
I recently found that the Fedora package has the exact same problem.

**Comment by Alexander-Wilms** [comment]
I tried to find the reason, but all I found that this info is defined here: https://github.com/sobotka/blender/blob/de13d0a80c3cb6a7445245b2999a29fe70e49953/source/blender/windowmanager/intern/wm_operators.c#L1403 

The value of build_hash seems to be defined here: https://github.com/sobotka/blender/blob/de13d0a80c3cb6a7445245b2999a29fe70e49953/source/creator/buildinfo.c#L34

And in turn, the value of BUILD_HASH is defined here: https://github.com/sobotka/blender/blob/593ed1347c96aea691eb503a6bbed12c801f3faa/build_files/cmake/buildinfo.cmake#L166

Maybe this is helpful

**Comment by bochecha** [comment]
This is what I get with 2.80:

![Screenshot from 2019-08-30 23-35-34](https://user-images.githubusercontent.com/272170/64049866-ecc28680-cb7e-11e9-80f8-e24a979af0ce.png)

It simply says "v2.80" in the top-right corner.

I get the exact same thing with the upstream binary release.

And indeed, the code was changed upstream to stop showing the build hash/date for stable releases: https://git.blender.org/gitweb/gitweb.cgi/blender.git/blobdiff/dc2b562ace25e77907c12c7a68bdc680bcf9a7e9..8d8ebc73b6668faddb1fa8d0bef678c611b5d535:/source/blender/windowmanager/intern/wm_operators.c

So I think we can close this now: I didn't actually fix anything, things just fixed themselves. :stuck_out_tongue:

**Comment by afranke** [comment]
> So I think we can close this now: I didn't actually fix anything, things just fixed themselves. stuck_out_tongue

C’est tombé en marche !

**Comment by bochecha** [comment]
> > So I think we can close this now: I didn't actually fix anything, things just fixed themselves. stuck_out_tongue
> 
> C’est tombé en marche !

Best kind of bug fixes!
