### ISSUE TITLE
Blenderkit no longer works under the current Blender version 4.0 cause libcrypt is missing

### ISSUE THREAD

**Issue by Knochestolle** [flathub/org.blender.Blender#166]
$ cat ~/.var/app/org.blender.Blender/data/blenderkit_data/daemon/daemon-62485.log 
/app/blender/4.0/python/bin/python3.10: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

blenderkit-v3.8.2.230906
Fedora release 38 (Thirty Eight)
Flatpak 1.15.4

$ flatpak info org.blender.Blender

Blender - Free and open source 3D creation suite

          ID: org.blender.Blender
         Ref: app/org.blender.Blender/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 4.0.0
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1.2 GB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

**Comment by kevinsmia1939** [comment]
Does this happen immediately after you try to install the addon?

**Comment by Knochestolle** [comment]
Hi @kevinsmia1939,

thanks for your answer, yes, right after the addon installation and also after restarting Blender.

Blender itself reports:
blenderkit ERROR: Unsuccessful Python check. Daemon will probably fail to run. [daemon_lib.py:613] [20:31:57.147, daemon_lib.py:613]

**Comment by kevinsmia1939** [comment]
Running this inside flatpak sandbox shows,
```
[📦 org.blender.Blender ~]$ /sbin/ldconfig -p | grep "crypt"
        libgcrypt.so.20 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20
        libcrypto.so.3 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcrypto.so.3
        libcrypt.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcrypt.so.2
```
which does not have libcrypt.so.1
This has been reported before.
https://github.com/BlenderKit/blenderkit/issues/530

The issue can be fix by installing compatibility package.
https://unix.stackexchange.com/questions/691479/how-to-deal-with-missing-libcrypt-so-1-on-arch-linux

But I not sure how can this be done without adding this dependency to flatpak manifest and rebuild it.

**Comment by barthalion** [comment]
See https://gitlab.archlinux.org/archlinux/packaging/packages/libxcrypt/-/blob/main/PKGBUILD?ref_type=heads#L31 for an inspiration. This would provide libcrypt.so.1.
