### ISSUE TITLE
blender flatpak does not appear in the app menu

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.blender.Blender#17]
Hi, I am in linuxmint 18.3, cinnamon desktop, I recently installed blender , but it does not appear in the apps menu. If I run this command : flatpak run org.blender.Blender, blender runs and the icon appears in the task bar, but no in the apps menu, graphics category

**Comment by Lvaskz** [comment]
1. I tried, but not work
2. Yes, I have many and they appears

**Comment by bochecha** [comment]
Alright, so there must be something wrong with the desktop file then. :confused: 

Do you have `/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop` or `~/.local/share/flatpak/exports/share/applications/org.blender.Blender.desktop`?

Can you paste its full content here?

Which other apps did you install from Flathub?

If you run `echo $XDG_DATA_DIRS` as your user in a terminal, what does it return?

**Comment by Lvaskz** [comment]
1. Which other apps did you install from Flathub? Mypaint, Gimp, VScode, Transmition.
2. If you run echo $XDG_DATA_DIRS as your user in a terminal, what does it return? 
/usr/share/cinnamon:/usr/share/gnome:/home/amiel/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop.
3. Do you have /var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop or ~/.local/share/flatpak/exports/share/applications/org.blender.Blender.desktop? No idea

**Comment by bochecha** [comment]
> Do you have /var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop or ~/.local/share/flatpak/exports/share/applications/org.blender.Blender.desktop? No idea

Well, can you look please? :confused: (and paste its full content)

**Comment by Lvaskz** [comment]
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop ( this one)
~ $ /var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 1: [Desktop: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 3: modeler: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 4: المنمذج: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 5: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 6: modelování: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 9: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 10: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 11: modelleerija: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 13: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 14: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 15: modellező: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 16: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 17: モデラー: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 18: modeliavimas: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 21: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 22: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 23: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 24: 3D-моделей: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 25: modelleyici: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 26: 3D-моделей: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 27: 3D: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 28: 建模: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 29: 模型: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 30: modeling,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 31: النمذجة،: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 32: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 33: modelatzea,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 34: прасторавага: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 35: মডেল,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 36: modeliranje,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 37: моделиране,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 38: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 39: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 40: modelleme,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 41: modelování,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 42: animation,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 43: Animation,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 44: animeren,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 45: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 46: animacio,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 47: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 48: modelleerimine,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 49: -animaatiot,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 50: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 51: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 52: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 53: modellek: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 54: hreyfimyndir,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 55: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 57: 모델링,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 58: modeliavimas,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 59: modelēšana,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 60: animasi,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 61: animasjon,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 62: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 63: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 64: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 65: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 66: animare,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 67: анимация,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 68: modeliranje,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 69: i: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 70: моделовање,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 71: animering,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 72: ஒப்புருவாக்கம்,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 73: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 74: modelleme,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 75: просторового: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 76: hình: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 77: 3D,: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 78: 模型、動畫、算圖和後製: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 79: 建模、动画、渲染和后期制作: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 80: 模型、動畫、算圖和後製: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: cg: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: modeling: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: animation: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: painting: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: sculpting: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: texturing: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: video: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: video: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: rendering: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: render: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: cycles: no se encontró la orden
/var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop: línea 81: game: no se encontró la orden

**Comment by bochecha** [comment]
Oh wow, you executed the file? :confused: 

I needed the content, which you can get with `cat /var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop`

**Comment by Lvaskz** [comment]
~ $ cat /var/lib/flatpak/exports/share/applications/org.blender.Blender.desktop
[Desktop Entry]
Name=Blender
GenericName=3D modeler
GenericName[ar]=3D المنمذج ثلاثي الأبعاد
GenericName[ca]=Modelador 3D
GenericName[cs]=3D modelování
GenericName[da]=3D-modellering
GenericName[de]=3D-Modellierer
GenericName[el]=Μοντελοποιητής 3D
GenericName[es]=Modelador 3D
GenericName[et]=3D modelleerija
GenericName[fi]=3D-mallintaja
GenericName[fr]=Modeleur 3D
GenericName[gl]=Modelador 3D
GenericName[hu]=3D modellező
GenericName[it]=Modellatore 3D
GenericName[ja]=3D モデラー
GenericName[lt]=3D modeliavimas
GenericName[nb]=3D-modellering
GenericName[nl]=3D-modeller
GenericName[pl]=Modelowanie 3D
GenericName[pt_BR]=Modelador 3D
GenericName[ro]=Arhitect 3D
GenericName[ru]=Редактор 3D-моделей
GenericName[tr]=3D modelleyici
GenericName[uk]=Редактор 3D-моделей
GenericName[wa]=Modeleu 3D
GenericName[zh_CN]=3D 建模
GenericName[zh_TW]=3D 模型
Comment=3D modeling, animation, rendering and post-production
Comment[ar]=3D النمذجة، الرسوم المتحركة، والتجسيد، وما بعد الإنتاج
Comment[ast]=Modeláu 3D, animación, renderizáu y postproducción
Comment[eu]=3D modelatzea, animazioa, errendatzea eta post-produkzioa
Comment[be]=Праграма прасторавага мадэлявання, анімацыі, апрацоўкі відэа і давядзення відэапрадукцыі
Comment[bn]=ত্রিমাত্রিক মডেল, অ্যানিমেশন, রেন্ডারিং এবং পোস্ট-উৎপাদন
Comment[bs]=3D modeliranje, animacija, obrada i postprodukcija
Comment[bg]=3D моделиране, анимиране, рендиране и пост-продукция
Comment[ca]=Modelat 3D, animació, renderització i post-producció
Comment[ca@valencia]=Modelat 3D, animació, renderització i post-producció
Comment[crh]=3B modelleme, animasyon, işleme ve son üretim
Comment[cs]=3D modelování, animace, rederování a postprodukce
Comment[da]=3D-modellering, animation, rendering og efterbehandling
Comment[de]=3D-Modellierung, Animation, Rendering und Nachbearbeitung
Comment[nl]=3d-modelleren, animeren, renderen en post-productie
Comment[el]=Μοντελοποίηση 3D, κινούμενα σχέδια, αποτύπωση και οργάνωση διαδικασίας μετά-την-παραγωγή
Comment[eo]=3D-modelado, animacio, renderado kaj postproduktado
Comment[es]=Modelado 3D, animación, renderizado y post-producción
Comment[et]=Kolmemõõtmeline modelleerimine, animeerimine, esitlemine ja järeltöötlemine
Comment[fi]=3D-mallinnus, -animaatiot, -renderöinti ja -tuotanto
Comment[fr]=Modélisation 3D, animation, rendu et post-production
Comment[fr_CA]=Modélisation 3D, animation, rendu et post-production
Comment[gl]=Modelado 3D, animación, renderizado e postprodución
Comment[hu]=3D modellek és animációk létrehozása és szerkesztése
Comment[is]=Þrívíddarmódel, hreyfimyndir, myndgerð og frágangur myndskeiða
Comment[it]=Modellazione 3D, animazione, rendering e post-produzione
Comment[ja]=3Dモデリング、アニメーション、レンダリング、ポストプロダクションのツール
Comment[ko]=3D 모델링, 애니메이션, 렌더링과 포스트 프로덕션
Comment[lt]=3D modeliavimas, animacijų kūrimas, atvaizdavimas ir tobulinimas
Comment[lv]=3D modelēšana, animācija, renderēšana un pēcapstrāde
Comment[ms]=Pemodelan, animasi, penerapan dan post-produksi 3D
Comment[nb]=3D-modellering, animasjon, rendering og postproduksjon
Comment[oc]=Modelizacion 3D, animacion, rendut e post-produccion
Comment[pl]=Modelowanie 3D, animacja, renderowanie i postprodukcja
Comment[pt]=Modelação 3D, animação, renderização e pós-produção
Comment[pt_BR]=Modelagem 3D, animação, renderização e pós-produção
Comment[ro]=Modelare, animare, afișare și post-producție 3D
Comment[ru]=3D-моделирование, анимация, рендеринг и компоновка
Comment[sl]=3D modeliranje, animacija, izrisovanje in nadaljnje obdelovanje
Comment[sq]=Animacion i modeleve 3D, rregullim dhe më pas prodhim
Comment[sr]=3Д моделовање, анимација, исцртавање и постпродукција
Comment[sv]=3d-modellering, animering, rendering och efterbehandling
Comment[ta]=முப்பரிமாண ஒப்புருவாக்கம், அசைவூட்டம், காட்சியாக்கம் மற்றும் உருவாக்கத்துக்கு பிந்தைய செயல்பாடுகள்
Comment[tg]=Моделсозии 3D, аниматсия, пешниҳод ва истеҳсоли баъдӣ
Comment[tr]=3B modelleme, animasyon, işleme ve son üretim
Comment[uk]=Програма просторового моделювання, анімації, обробки відео та доведення відеопродуктів
Comment[vi]=Tạo hình mẫu 3D, hoạt họa, dựng hình và các công việc hậu kỳ
Comment[wa]=Modelaedje 3D, animåcion, rindou eyet après-produccion
Comment[zh_HK]=3D 模型、動畫、算圖和後製
Comment[zh_CN]=3D 建模、动画、渲染和后期制作
Comment[zh_TW]=3D 模型、動畫、算圖和後製
Keywords=3d;cg;modeling;animation;painting;sculpting;texturing;video editing;video tracking;rendering;render engine;cycles;game engine;python;
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=blender --file-forwarding org.blender.Blender @@ %f @@
Icon=org.blender.Blender
Terminal=false
Type=Application
Categories=Graphics;3DGraphics;
MimeType=application/x-blender;
X-Flatpak=org.blender.Blender
amiel@amiel-Inspiron-3442 ~ $

**Comment by bochecha** [comment]
Thanks.

I thought maybe some problem had happened while installing Blender and your file was somehow truncated, but no, that's the right content.

I have no other idea at this point. :disappointed:

**Comment by Lvaskz** [comment]
Well, Now I am in ubuntu 18.04, it is working here
