### ISSUE TITLE
Blender 4.1 crashes when using Wayland and Nvidia

### ISSUE THREAD

**Issue by peterdk** [flathub/org.blender.Blender#176]
I just updated Blender 4.0 to 4.1 using this Flatpak. Unlike 4.0, this immediately crashes the whole window manager at startup when showing the start settings dialog. Using Nvidia, Wayland on Ubuntu 23.10.

Error message shown when I log the flatpak run command:
The Wayland connection experienced a fatal error: Protocolfout

Probably not related to the flatpak itself, but who knows.

**Comment by kevinsmia1939** [comment]
What distro are you using?

**Comment by kevinsmia1939** [comment]
It could be that system's nvidia driver and in flatpak does not match. Have you tried updating flatpak? `flatpak update`

**Comment by peterdk** [comment]
I tried X11, there it works properly.
Maybe blender uses some new Wayland protocol that Nvidia doesn't support yet.

I did indeed run flatpak update, but no updates for Nvidia. I use latest Nvidia driver from the nvidia ppa.

Oh, I use the beta of Ubuntu 24.04 I realized. But that should not be the issue? I'll try the fedora install I also have

**Comment by peterdk** [comment]
I just tested Fedora, there it works. And went back to Ubuntu, and ala a new Nvidia driver update is there today. That fixed it after also updating flatpak. (Nvidia 550-67)
