### ISSUE TITLE
In blender (wayland) the mouse pointer is displayed smaller than it should be. With x11 it is normal

### ISSUE THREAD

**Issue by TheRsKing** [flathub/org.blender.Blender#177]
openSUSE Aeon
gnome 46

**Comment by kevinsmia1939** [comment]
screenshot?

**Comment by TheRsKing** [comment]
it happens a bit with 100% scaling.:
[100% scaled.webm](https://github.com/flathub/org.blender.Blender/assets/130909958/78938339-ce39-4625-b3b4-9437d1484dde)

but it becomes a real problem at 125% scaled:
[125% scaled.webm](https://github.com/flathub/org.blender.Blender/assets/130909958/c3d2790d-bda2-4d2e-8e2f-913777d8ea59)

if i remove the wayland rights it works(125% scaling):
[wayland off 125% scaled.webm](https://github.com/flathub/org.blender.Blender/assets/130909958/0b5e5985-3a25-4845-acdd-0717c2c381db) 
![wayland off](https://github.com/flathub/org.blender.Blender/assets/130909958/2a6771a1-24aa-47aa-bd0b-641d068f6c76)

**Comment by kevinsmia1939** [comment]
Just to be sure, Blender from openSUSE repo looks fine?

**Comment by TheRsKing** [comment]
I installed it in distrobox (tumbleweed repo) and everything was normal there

**Comment by TheRsKing** [comment]
I just noticed that distrobox also only started in x11, I installed it via rpm and the bug is there too. I will report the bug to blender itself

**Comment by kevinsmia1939** [comment]
Ok, since the bug is upstream, I think we can close this one.
