### ISSUE TITLE
 spacenavd not working with blender .. Is this compiled with spacenav support?

### ISSUE THREAD

**Issue by japrogramer** [flathub/org.blender.Blender#18]
hello I am on linux, I run blender from the flathub flatpak
like this 

```
$XAUTHORITY=$HOME/.Xauthority sudo spacenavd -v -d
$flatpak run org.blender.Blender
```

is it because it runs in a jail that it cant detect the magic sauce that spacenavd is doing

**Comment by bochecha** [comment]
What if you run Blender with the following command?

```
$ flatpak run --device=all org.blender.Blender
```

**Comment by bochecha** [comment]
Seems another problem is that we build Blender with `-DWITH_INPUT_NDOF:BOOL=OFF`.

To enable that, we'd have to add the Spacenav libraries to the build.

I'll try to have a go at this.

**Comment by bochecha** [comment]
@japrogramer Since I don't have the spacenab hardware I can't reproduce the problem or try to debug it.

However, maybe you can help me. :slightly_smiling_face: 

I'd like you to do the following, if possible:

1.  uninstall Blender from Flathub:

    ```
    $ flatpak uninstall org.blender.Blender
    ```

2.  download and install a bundle I just made for testing purposes:

    ```
    $ wget https://www.daitauha.fr/static/blender.flatpak
    $ flatpak install --user blender.flatpak
    Installing for user: org.blender.Blender/x86_64/spacenav from bundle blender.flatpak
    ```

3.  run the test build:

    ```
    $ flatpak run org.blender.Blender//spacenav
    ```

Do things work?

**Comment by japrogramer** [comment]
@bochecha finally had the chance to install and run, it didn't work ..
I ran the program like you suggested and tha I ran it with all the devices passed like in the first comment

here is everything in my set up
```

▶ xauth -vib generate :0 . trusted
Attempting to break locks on authority file /home/archangel/.Xauthority
Ignoring locks on authority file /home/archangel/.Xauthority
authorization id is 1024
Ignoring locks and writing authority file /home/archangel/.Xauthority

~/Downloads
▶ XAUTHORITY=$HOME/.Xauthority sudo spacenavd -v -d
Spacenav daemon 0.6
failed to open config file /etc/spnavrc: No such file or directory. using defaults.
Device detection, parsing /proc/bus/input/devices
found usb device [46d:c626]: "3Dconnexion SpaceNavigator" (/dev/input/event17)
adding device.
device name: 3Dconnexion SpaceNavigator
  Number of axes: 6
using device: /dev/input/event17
trying to open X11 display ":0"
   XAUTHORITY=/home/archangel/.Xauthority
adding dev event for device: /dev/input/event17
```
`flatpak run --device=all org.blender.Blender//spacenav`

**Comment by bochecha** [comment]
Oh sorry, I missed it.

Did you get any output in the terminal when running Blender? Maybe try with `--debug-all`? (that might make it extremely verbose)

**Comment by Arxcis** [comment]
@bochecha Blender does not listen to the device directly. The `spacenavd` events are sent across the X11 socket (for compability with clients talking to the closed source driver) and a Unix domain socket for features only available in the `spacenavd`-driver.

Programs that use [ibspnav](https://github.com/FreeSpacenav/libspnav) have the option to use either the legacy X11-mode or the Unix socket mode.  

According to the https://github.com/FreeSpacenav/spacenavd#dependencies, Blender is utliizing the Unix socket.

The path to the Unix socket is defined in https://github.com/FreeSpacenav/libspnav/blob/master/spnav.c#L39
```c
#define SPNAV_SOCK_PATH "/var/run/spnav.sock"
```

**Comment by Arxcis** [comment]
I tried
```
$ flatpak run --filesystem=/var/run/spnav.sock --user org.blender.Blender//spacenav 
bwrap: Can't make symlink at /var/run: File exists
```
Does that mean that the socket is available inside the flatpak?

**Comment by E-Bachman** [comment]
Did anyone figure out how to make it work with blender flatpak?

**Comment by adrianinsaval** [comment]
posting in case it's relevant, socket path seems to be configurable now: https://github.com/FreeSpacenav/libspnav/releases/tag/v0.3

**Comment by ananace** [comment]
I added the support into FreeCAD with https://github.com/flathub/org.freecadweb.FreeCAD/pull/55 - the exact same changes should work for Blender as well.

**Comment by tkrill** [comment]
@ananace comment solves this for me.

> `flatpak override --user org.blender.Blender --filesystem=/run/spnav.sock:ro`

Could this permission somehow be integrated in the flatpak build?

**Comment by adrianinsaval** [comment]
I do not have a 3d mouse so I cannot test, those of you who have it please test this PR: https://github.com/flathub/org.blender.Blender/pull/131#issuecomment-1366221802

**Comment by tkrill** [comment]
@adrianinsaval i downloaded and tested the version with the PR above. Seems to work for me.

**Comment by Arxcis** [comment]
Thank you very much @adrianinsaval :clap: for implementation and @tkrill for testing :smile:
