### ISSUE TITLE
Update flatpack package to Blender 4.2 LTS ?

### ISSUE THREAD

**Issue by lirtistan** [flathub/org.blender.Blender#185]
Hi,

is there a plan on updating Blender from 4.1.1 to 4.2, if so when can we expect that!?
I want that Material Displacement feature inside EEVEE ❤️

**Comment by lirtistan** [comment]
Its already in snapstore, see https://snapcraft.io/blender

**Comment by kevinsmia1939** [comment]
Check out https://github.com/flathub/org.blender.Blender/pull/184

**Comment by lirtistan** [comment]
I close here. (https://github.com/flathub/org.blender.Blender/pull/184)
