### ISSUE TITLE
Need reference to old desktop ID to fix gnome-software and the ODRS

### ISSUE THREAD

**Issue by hughsie** [flathub/org.blender.Blender#27]
In Fedora, the application ID is `blender.desktop` but on flatpak it is `org.blender.Blender`. To "merge" the old and new IDs together in front-ends like gnome-software and KDE discover, and to use reviews reported against the old ID with the new ID you need to add an line in the existing `provides` section in the metainfo.xml file:

    <provides>
      <id>blender.desktop</id>
    </provides>

See https://blogs.gnome.org/hughsie/2017/07/05/using-a-reverse-style-application-ids-in-your-application/ for more details.

**Comment by bochecha** [comment]
Thanks for the issue @hughsie.

I had been meaning to do that for a long time, but kept forgetting it, so this is the reminder I needed. :slightly_smiling_face:
