### ISSUE TITLE
Flatpak blender package cant find OpenGL 3.3

### ISSUE THREAD

**Issue by hcw70** [flathub/org.blender.Blender#31]
System Information
Operating system: Ubuntu 19.04
Graphics card: NVidia PRIME Laptop (GeForce GTX 960M (GPU 0))

Blender Version
Broken: 2.80 installed via flatpak
Worked: 2.80 installed via download of blender-2.80-linux-glibc217-x86_64.tar.bz2

Short description of error

When starting blender from flatpak i get the error:

Error! Unsupported graphics card or driver.
A graphics card and driver with support for OpenGL 3.3 or higher is required.

Exact steps for others to reproduce the error

On a PRIME laptop with the graphics card mode set to "NVIDIA" try to start blender 2.80.

Complete console printout on startup:
```

hcw@nvidion:~/Blender/blender-2.8$ flatpak run org.blender.Blender
/run/user/1000/gvfs/ non-existent directory
Read prefs: /home/hcw/.var/app/org.blender.Blender/config/blender/2.80/config/userpref.blend
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Received X11 Error:
error code: 8
request code: 152
minor code: 34
error text: BadMatch (invalid parameter attributes)
Received X11 Error:
error code: 8
request code: 152
minor code: 34
error text: BadMatch (invalid parameter attributes)
Received X11 Error:
error code: 8
request code: 152
minor code: 34
error text: BadMatch (invalid parameter attributes)
Received X11 Error:
error code: 8
request code: 152
minor code: 34
error text: BadMatch (invalid parameter attributes)
Received X11 Error:
error code: 8
request code: 152
minor code: 34
error text: BadMatch (invalid parameter attributes)
Received X11 Error:
error code: 8
request code: 152
minor code: 34
error text: BadMatch (invalid parameter attributes)
Received X11 Error:
error code: 8
request code: 152
minor code: 34
error text: BadMatch (invalid parameter attributes)
Error! Unsupported graphics card or driver.
A graphics card and driver with support for OpenGL 3.3 or higher is required.
The program will now close.
```

**Comment by hcw70** [comment]
BTW, the snap version also works ok. Only issue via flatpak.

**Comment by bochecha** [comment]
The reason the upstream tarball works is that it runs directly on the host (not in a sandbox) and as a result has direct access to the drivers. The snap might be in that case as well.

You use the proprietary nvidia driver?

If yes, can you run the following on your machine?

```
$ flatpak list --all | grep -i nvidia
```

**Comment by hcw70** [comment]
```
hcw@nvidion:~$ flatpak list --all | grep -i nvidia
nvidia-390-116	org.freedesktop.Platform.GL.nvidia-390-116		1.4	flathub	system
nvidia-390-77	org.freedesktop.Platform.GL.nvidia-390-77		1.4	flathub	system
nvidia-430-40	org.freedesktop.Platform.GL.nvidia-430-40		1.4	flathub	system

```

For snap i had to do 
`snap install --classic blender
`
So it may have full access.

On the host i use nvidia-driver-430 from ubuntu.

**Comment by bochecha** [comment]
> For snap i had to do
>     snap install --classic blender
> So it may have full access.

Indeed, that gives it full access, as it runs essentially unsandboxed. Flatpak doesn't have an unsandboxed mode, we need to poke appropriate holes in the sandbox to get things working.

> On the host i use nvidia-driver-430 from ubuntu.

Ok, and you have that extension installed: `org.freedesktop.Platform.GL.nvidia-430-40`

At this point I will need to investigate a bit, not sure why this doesn't work for you. :confused:

**Comment by hcw70** [comment]
Maybe related: https://github.com/flatpak/flatpak/issues/138 ?

**Comment by p1u3o** [comment]
What does the output of 
```
flatpak run --command=ls org.blender.Blender /usr/lib/x86_64-linux-gnu/GL/ 
```
give you?

**Comment by hcw70** [comment]
```
hcw@nvidion:~$ flatpak run --command=ls org.blender.Blender /usr/lib/x86_64-linux-gnu/GL/ 
glvnd  nvidia-430-40  OpenCL  vulkan

```

**Comment by RexoWeb** [comment]
NowBlender Released New Version Blender 2.80 with New Interface and with Many New Interesting Features. But with this Version  #**Peoples are Facing Some Problems Like a Big Problem is Graphics Card Problem or Opengl 3.3 Error**. For Using Blender 2.80 You Need a Good PC with Good Graphics Card that Support OpenGL 3.3.

### **But Don’t Worry Here I am Showing How You Can Run Blender 2.8 Without Graphics Card. How to Run Blender 2.8 Without OpenGL 3.3.** how to fix blender opengl 3.3 error.

**For Using Blender 2.80 Without Graphics Card or Without Opengl 3.3 Error You Need to Follow Some Steps.**

[_**Continue Reading...**_](https://www.rexoweb.com/how-to-run-blender-2-8-without-graphics-card/)

**Comment by bochecha** [comment]
@RexoWeb that comment is off-topic as the article talks about Windows and doesn't apply to Flatpak.

It's also not something we should recommend: downloading a random OpenGL library from a Google Drive and replacing the normal one with it is terrible security practice. Who knows what that library really does?

Finally, the fact you point to an article on your own website and then yourself add positive reactions to your comment makes me wonder if you're not just a spammer.

Please do not do any of that here any more.

**Comment by eszlari** [comment]
Maybe related to: https://github.com/flatpak/flatpak/issues/869

**Comment by plafue** [comment]
Hi there :wave: This issue has been open for a while....

@hcw70 could you please test if the error persists with the latest published version?

**Comment by hcw70** [comment]
@plafue Blender now starts with version 2.93.0 ok.
But preferences says it is unable to find my NVIDIA gpu.

**Comment by hcw70** [comment]
Ok, gpu did not work in snap also.... 
But after reboot, all is fine.
So this was a problem of my gpu....
