### ISSUE TITLE
blender 2.81 stable is out

### ISSUE THREAD

**Issue by iman-salmani** [flathub/org.blender.Blender#40]

**Comment by bochecha** [comment]
Yes, I know, thanks.

**Comment by fikrillah** [comment]
been waiting for several days, till i decided to open an issue moment ago lol...

**Comment by bochecha** [comment]
> been waiting for several days

Oh wow, so sorry to make you wait for such an excruciatingly long time! My apologies for having a life outside this stuff. :roll_eyes: 

I've set some time to work on this next week, I hope this isn't too far away for you.
