### ISSUE TITLE
Add yofrankie as extension

### ISSUE THREAD

**Issue by damianatorrpm** [flathub/org.blender.Blender#45]
Please add yofrankie as an optional extension, it is most suited here as it requires blender IIRC

**Comment by bochecha** [comment]
Thanks for the suggestion.

However, what is yofrankie and what does it bring to Blender users? Is it a very common extension?

**Comment by damianatorrpm** [comment]
https://www.google.com/search?q=yofrankie
Yofrankie is the Blender showcase "application"

**Comment by damianatorrpm** [comment]
https://en.wikipedia.org/wiki/Yo_Frankie!
> Yo Frankie! is an open source video game made by the Blender Institute, part of the Blender Foundation

**Comment by damianatorrpm** [comment]
https://build.opensuse.org/package/show/games/yofrankie

**Comment by damianatorrpm** [comment]
> Thanks for the suggestion.
> 
> However, what is yofrankie and what does it bring to Blender users? Is it a very common extension?

The best place for this to be is as an ExtensionOf blender which defaults to not auto install

**Comment by bochecha** [comment]
> The best place for this to be is as an ExtensionOf blender which defaults to not auto install ?
> Or a separate application that builds blender, removes blender.desktop)

Oh, so it comes with its own `.desktop` file? In that case that doesn't feel like an extension (for which the normal UX would be to load it inside the main Blender window) but like an entirely separate app, which should be maintained in its own repository.

Something like `org.blender.YoFrankie` maybe?

I personally don't have the time to do that, I'll be happy to help figure out how we can share as much as possible from the Blender manifest.

**Comment by ricvelozo** [comment]
From version 2.80, Blender don't have a game engine anymore. And YoFrankie itself is very old (latest version released in July 2009).

**Comment by bochecha** [comment]
> From version 2.80, Blender don't have a game engine anymore.

If that's the case, then I guess there is nothing we can do about it, so let's close this issue.
