### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.blender.Blender#55]
This repository is dead?
We are in version 2.83.5

**Comment by Eonfge** [comment]
Don't forget the dependencies, there are also outdated versions of FFmpeg and such included

**Comment by alexb3d** [comment]
2.90 standard version
2.83.5 LTS version

**Comment by Eonfge** [comment]
Flathub, aimed at destkop usage, should use the 2.90 standard version if you ask me. 

2.83.5 is for servers and render farms, in which case you should use docker/podman, or just run it directly on the host.

**Comment by alexb3d** [comment]
The LTS will also be used by animation studios that need a stable workflow, and will receive important updates. It would be advisable to have both branches of Blender in Flatpak.

**Comment by barthalion** [comment]
Just pushed 2.83.5 but I don't have capacity to properly maintain it and keep all dependencies up to date. I've opened a PR switching the manifest to binary build at https://github.com/flathub/org.blender.Blender/pull/57.

I agree that latest version is what majority of users would expect; LTS could be provided under a different app id if there is a need.

**Comment by alexb3d** [comment]
Thanks barthalion.
It seems to me that yes, the LTS is important because it is focused on a professional sector and is maintained by Blender.
Is it okay if I ask for help from the blender community to maintain these repositories?

**Comment by barthalion** [comment]
@alexb3d I think the most sustainable would be to re-submit current manifest with `org.blender.BlenderLTS` appid. Also yes, it would be vastly preferred if both packages could be maintained by someone who knows Blender.

**Comment by barthalion** [comment]
Either way, 2.83.5 has been pushed yesterday for x86_64 and aarch64, and I just merged the PR switching the manifest to official binary build for 2.90 (only x86_64 but it is what it is).
