### ISSUE TITLE
Not working on Nouveau

### ISSUE THREAD

**Issue by xerz-one** [flathub/org.blender.Blender#59]
Despite the official build from blender.org working, trying to run the Flatpak build of 2.90 on an iMac Late 2009 with an Nvidia GeForce 9400M returns the following error:

    /usr/include/c++/10.2.0/bits/stl_deque.h:1326: std::deque<_Tp, _Alloc>::reference std::deque<_Tp, _Alloc>::operator[](std::deque<_Tp, _Alloc>::size_type) [with _Tp = nv50_ir::ValueRef; _Alloc = std::allocator<nv50_ir::ValueRef>; std::deque<_Tp, _Alloc>::reference = nv50_ir::ValueRef&; std::deque<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

This has been tested in Debian Sid (system Mesa: 20.1.6) and GNOME OS (system Mesa: 20.1.7). The issue was not found with Intel graphics (Surface Pro 5, Intel HD Graphics 620) or VirtIO (QEMU 5.1.0 on the Surface).

**Comment by eszlari** [comment]
The Mesa nouveau driver is part of the runtime, please open a bug report there:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues
