### ISSUE TITLE
Missing Python requests module

### ISSUE THREAD

**Issue by brechtvl** [flathub/org.blender.Blender#6]
Official Blender releases are bundled with the Python requests module, which some bundled and third party addons rely on. This module appears to be missing from the flatpak version and causes errors:

Originally reported here:
https://developer.blender.org/T53981

Bundled Python modules are: `idna`, `chardet`, `urllib3`, `certifi`, `requests` and `numpy`, see:
https://developer.blender.org/diffusion/B/browse/master/build_files/build_environment/cmake/python_site_packages.cmake
https://developer.blender.org/diffusion/B/browse/master/build_files/build_environment/cmake/versions.cmake

**Comment by bochecha** [comment]
I had voluntarily left out those Python modules when I flatpaked Blender, because I didn't know how Blender addons work and decided I'd figure it out later.

Seems we now reached that "later" time, so thanks for the report. 🙂 

I assume there is no dependency management when installing an addon? Do addons expect those modules to be present? Does Blender upstream consider those modules to be part of the API they provide for addons?

**Comment by brechtvl** [comment]
There is no dependency management. These modules are considered to be part of the API provided for addons, and expected to be available. Bundled addons like Blender ID and Sketchfab use the `requests` module.

**Comment by bochecha** [comment]
Ok, thanks for confirming. 🙂

**Comment by bochecha** [comment]
@brechtvl Only partially related, is this what was used to make the Blender 2.79 official upstream builds?

https://developer.blender.org/diffusion/B/browse/master/build_files/cmake/config/blender_release.cmake;8ef39d5c882896bd75e0d4d17fb3e3d4710fc768

Or is it another file here:

https://developer.blender.org/diffusion/B/browse/master/build_files/cmake/config/;8ef39d5c882896bd75e0d4d17fb3e3d4710fc768

**Comment by brechtvl** [comment]
It's `blender_release.cmake`.

**Comment by bochecha** [comment]
Thanks @brechtvl for all the information.

This should now be fixed as soon as the build finishes: https://flathub.org/builds/#/builders/1/builds/2038

**Comment by brechtvl** [comment]
Great, thanks!

**Comment by EmJayAu** [comment]
Hiya Bochecha,
I'm the culprit of reporting the prob to Brecht.
Just a quicky... Is build 2038 already available on flathub? Cause I checked and it doesn't state the current build...???
Let us know, would ya??
Thanx a lot,
Cheers, Mate!!

**Comment by bochecha** [comment]
@EmJayAu I just updated to the latest Blender on Flathub, and it does have the Python modules you were missing:

```
$ ls -1 /var/lib/flatpak/app/org.blender.Blender/current/active/files/lib/python3.5/site-packages/
certifi
certifi-2017.7.27.1-py3.5.egg-info
chardet
chardet-3.0.2-py3.5.egg-info
idna
idna-2.6-py3.5.egg-info
numpy
numpy-1.10.4-py3.5.egg-info
PyOpenColorIO.so
requests
requests-2.18.4-py3.5.egg-info
urllib3
urllib3-1.22-py3.5.egg-info
```

**Comment by EmJayAu** [comment]
Hiya Bochecha,
Thanx a million, Mate!!
Have a G'Day!!
Cheers,

EmJay
