### ISSUE TITLE
Won't open file from Nautilus

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.blender.Blender#61]
When opening a file from Nautilus with a double click, Blender opens with the default scene but the file does not.

PS: 2.90.1 is out. I have had no luck with the Blender community to help with Flatpak :/

**Comment by jesterKing** [comment]
Wild guess:

https://github.com/flathub/org.blender.Blender/blob/master/org.blender.Blender.json#L178

needs to read something like "exec ./blender \"$@\"". Adjusted for correct syntax needed in json to work with this...

Reference https://developer.blender.org/T81304#1025974

**Comment by jesterKing** [comment]
I see this is already handled with PR #60

**Comment by alexb3d** [comment]
@bilelmoussaoui The problem persists. Why are you closing it?
