### ISSUE TITLE
Can't install Blender 2.91 from Ubuntu 20.04 software center chksum error

### ISSUE THREAD

**Issue by stillpointx** [flathub/org.blender.Blender#64]
System Information
Operating system: Linux-5.4.0-54-generic-x86_64-with-debian-bullseye-sid 64 Bits
Graphics card: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2) Intel Open Source Technology Center 4.5 (Core Profile) Mesa 20.0.8

Blender Version
Broken: version: 2.91.0, branch: master, commit date: 2020-11-25 08:34, hash: rB0f45cab862b8

Short description of error
Can't install Blender 2.91 from Ubuntu 20.04 software center chksum error

![image](https://user-images.githubusercontent.com/28985314/100434254-3348ae80-306a-11eb-8aa1-97db7b8e1c0a.png)

![error screenshot-2020-11-26-12-35-13](https://user-images.githubusercontent.com/28985314/100434161-13b18600-306a-11eb-94d7-ddc396898db3.png)

**Comment by eszlari** [comment]
Does it work from the command line?

```
$ flatpak install blender
```

**Comment by stillpointx** [comment]
Yes this did work.  I'm not sure way the issue occurs with the GUI.

```
rt@sys76:~$ flatpak install blender

Looking for matches…
Found similar ref(s) for ‘blender’ in remote ‘flathub’ (system).
Use this remote? [Y/n]: y
Similar refs found for ‘blender’ in remote ‘flathub’ (system):

   1) runtime/org.blender.Blender.Codecs/x86_64/stable
   2) app/org.blender.Blender/x86_64/stable

Which do you want to use (0 to abort)? [0-2]: 2

org.blender.Blender permissions:
    ipc                  network      pulseaudio      x11     dri
    file access [1]

    [1] host


        ID                           Branch          Op         Remote          Download
 1. [✓] org.blender.Blender          stable          i          flathub         203.6 MB / 210.8 MB

Installation complete.

flatpak run org.blender.Blender

```
