### ISSUE TITLE
Installing python3.7 so it will work with Blender 2.91 and it's addons

### ISSUE THREAD

**Issue by stillpointx** [flathub/org.blender.Blender#65]
I was wondering if flatpak allows installing / giving Blender access to other programs like python3.7
I ran into issues with using the snap package and was wondering if flatpak may have a workaround.

The error i get running Blender 2.91.0 flatpak while trying to install some addons
****ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory****

Discussion with Blender:
https://developer.blender.org/T83085

Discussion with Animation Node Blender addon maintainer: 
https://github.com/JacquesLucke/animation_nodes/issues/1595

Disscussion with Snap:
https://forum.snapcraft.io/t/blender-2-91-with-python-3-7-and-ubuntu-20-04-and-plugins-snap-issues/21347

**Comment by eszlari** [comment]
The official build doesn't ship this file, therefore this is not a flatpak specific problem.

**Comment by stillpointx** [comment]
Is there a way to add it to the flatpak? Or a possible workaround?

**Comment by eszlari** [comment]
That file should come bundled with the addon.

**Comment by plafue** [comment]
Hi there :wave: This issue has been open for a while....

Python 3.9.2 is bundled with the last flatpak release. Is this issue still relevant @stillpointx ?

**Comment by stillpointx** [comment]
I switched to using the snap and it works with Blender 2.93.0 haven't tried with the flatpak version.

**Comment by plafue** [comment]
We'll reopen this if we have any further incompatibility reports.
