### ISSUE TITLE
Update to the latest version

### ISSUE THREAD

**Issue by lumingzh** [flathub/org.blender.Blender#78]
Blender 2.93.3 was released on August 18, please update to the latest version.

Thank you.

**Comment by kevinsmia1939** [comment]
here https://github.com/flathub/org.blender.Blender/pull/79
let me know if it work correctly.

**Comment by jimmac** [comment]
3.0 just released ;)

**Comment by kevinsmia1939** [comment]
PR for 3.0 is here https://github.com/flathub/org.blender.Blender/pull/87
closing this one.
