### ISSUE TITLE
3.0.1 availability?

### ISSUE THREAD

**Issue by unholyeyebrows** [flathub/org.blender.Blender#93]
Hi - Blender 3.0.1 was released upstream about a week ago but the Flatpak has not caught-up. It looks like a build has been attempted but failed. What can be done to solve the issues and get 3.0.1 release?

Many thanks
Nick

**Comment by mbridon** [comment]
As the original maintainer of the Flathub build, personal circumstances have left me unavailable for this, so I'll need to wait the awesome Flathub community to pick this up, unless I can get enough time available this weekend, but given how long a full build of Blender and its deps take, I'm not hopeful 😕

**Comment by unholyeyebrows** [comment]
No worries - appreciate life takes priority - all the best.
